sink("output/masterRun.txt")
setwd("code")
source("packages.r", echo=FALSE)
source("summary.R", echo=FALSE)
source("main_analysis.R", echo=FALSE)
source("main_tables_figures.R", echo=FALSE)
source("vdem_partof_table5.R", echo=FALSE)
source("table5.R", echo=FALSE)
source("table6.R", echo=FALSE)
source("appendixD1.R", echo=FALSE)
source("appendixD2.R", echo=FALSE)
source("appendixD3.R", echo=FALSE)
source("appendixD5.R", echo=FALSE)
setwd("..")
sink()
